/**
 * Demo Reclaim claim fixture. Generated by packages/circuits/src/generate-fixture.ts
 * using a freshly-minted secp256k1 key. Not tied to the canonical Reclaim attestor
 * (0x244897...9072) — this fixture's witness.id is the demo key's address, so the
 * proof binds to this demo attestor. Use the real Reclaim SDK for production.
 */
export const DEMO_RECLAIM_CLAIM_JSON = JSON.stringify(
  {
    identifier:
      '0xd0238f52d04e2331e34ad739b53543ba001901362977716de7cd7fb93d37bb8b',
    claimData: {
      provider: 'github',
      parameters: '{"username":"kvkthecreator"}',
      context:
        '{"contextAddress":"0x0","contextMessage":"demo","extractedParameters":{"username":"kvkthecreator"}}',
      owner: '0x0000000000000000000000000000000000000000',
      timestampS: 1776569286,
      epoch: 1,
      identifier:
        '0xd0238f52d04e2331e34ad739b53543ba001901362977716de7cd7fb93d37bb8b',
    },
    signatures: [
      '0x654878eca7d120bc230929cdf6e77b7f3083fe652f8efa6fbde7739a18fe4ed3ea34217b2ce3e51492cd1a8a965bed41f5c88d9226c733afeb14c3201a3b6e5c1b',
    ],
    witnesses: [
      {
        id: '0x9750148c76c1cf11014c90b9ba6b4b4fddb87766',
        url: 'https://demo-attestor.example',
      },
    ],
    extractedParameters: { username: 'kvkthecreator' },
  },
  null,
  2
);
